SportStore/WebUI/Controllers/NavController.cs
using DomainModel.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductsRepository productsRepository;
        public NavController(IProductsRepository productsRepository) 
        {
            this.productsRepository = productsRepository;
        }
        public ViewResult Menu(string highlightCategory)
        {
            // Поместить в начало ссылку Home
            List<NavLink> navLinks = new List<NavLink>();
            navLinks.Add(new CategoryLink(null) { IsSelected = (highlightCategory == null) });
            //добавить ссылку для каждой отличающейся категории
            var categories = productsRepository.Products.Select(x => x.Category);
            foreach (string category in categories.Distinct().OrderBy(x=>x))
            {
                navLinks.Add(new CategoryLink(category) { IsSelected = (category == highlightCategory) });
            }
            return View(navLinks);
        }
    }

    public class NavLink // представляет ссылку на произвольный элемент маршрута
    {
        public string Text { get; set; }
        public RouteValueDictionary RouteValues { get; set; }
        public bool IsSelected { get; set; }
    }

    public class CategoryLink : NavLink // специфическая ссылка на категорию товаров
    {
        public CategoryLink(string category)
        {
            Text = category ?? "Home";
            RouteValues = new RouteValueDictionary(new
            {
                controller = "Products",
                action = "List",
                category = category,
                page = 1
            });
        }
    }
}

SportStore/WebUI/Controllers/ProductsController.cs
using DomainModel.Abstract;
using DomainModel.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class ProductsController : Controller
    {
        public int PageSize = 1; // позже изменим
        private IProductsRepository productsRepository;

        public ProductsController(IProductsRepository productRepository)
        {
            // это временно пока не будет готова инфраструктура
            //string connString = @"Data Source=ALEX-PC\SQLEXPRESS;Initial Catalog=SportStore;Integrated Security=True";
            //productsRepository = new SqlProductRepository(connString);
            this.productsRepository = productRepository;
        }

        public ViewResult List(string category, int page)
        {
            var productsInCategory = (category == null) ? productsRepository.Products : productsRepository.Products.Where(x => x.Category == category);

            int numProducts = productsInCategory.Count();
            ViewBag.TotalPages = (int)Math.Ceiling((double)numProducts / PageSize);
            ViewBag.CurrentPage = page;
            ViewBag.CurrentCategory = category; // для использования при генерации ссылок на страницы

            return View(productsInCategory
                        .Skip((page-1) * PageSize)
                        .Take(PageSize)
                        .ToList());
        }
    }
}

SportStore/WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<WebUI.Controllers.NavLink>

@foreach (var link in Model)
{
    <a href="@Url.RouteUrl(link.RouteValues)"  class="@(link.IsSelected ? "selected" : "")" >
        @link.Text 
    </a>
}

SportStore/WebUI/Views/Products/List.cshtml
@using System.Collections
@using WebUI.HtmlHelpers

@model IEnumerable<DomainModel.Entities.Product>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/Site.cshtml";
}

<h2> @(string.IsNullOrEmpty((string)ViewBag.CurrentCategory) ? "All products" : Html.Encode(ViewBag.CurrentCategory))</h2>

@foreach (var product in Model)
{
    Html.RenderPartial("ProductSummary", product);
}


<div class="pager">
    Page:
    @Html.PageLinks((int)ViewBag.CurrentPage,
                    (int)ViewBag.TotalPages,
                    x => Url.Action("List", new { page = x, category = ViewBag.CurrentCategory }))
</div>

SportStore/WebUI/Views/Shared/ProductSummary.cshtml
@model DomainModel.Entities.Product


    <div class="item">
        <h3>@Model.Name</h3>
        @Model.Description
        <h4>@Model.Price.ToString("c")</h4>
    </div>

SportStore/WebUI/Views/Shared/Site.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        body {
            font-family: Cambria, Georgia, "Times New Roman";
            margin: 0;
        }
        div#header div.title, div.item h3, div.item h4, div.pager a {
            font: bold 1em "Arial Narrow", "Franklin Gothic Medium", Arial;
        }
        div#header {background-color: #444; border-bottom: 2px solid #111; color: white;}
        div#header div.title {font-size: 2em; padding: .6em;}
        div#content {border-left: 2px solid gray; margin-left: 9em; padding: 1em;}
        div#categories {float: left; width: 8em; padding: .3em;}
        div.itme {border-top: 1px dotted gray; padding-top: .7em; margin-bottom: .7em;}
        div.item:first-child {border-top: none; padding-top: 0;}
        div.item h3 {font-size: 1.3em; margin: 0 0 .25em 0;}
        div.item h4 {font-size: 1.1em; margin: .4em 0 0 0;}
        div.pager {text-align:right; border-top: 2px solid silver; padding: .5em 0 0 0; margin-top: 1em;}
        div.pager a {font-size: 1.1em; color: #666; text-decoration: none; padding: 0 .4em 0 .4em;}
        div.pager a:hover {background-color: silver;}
        div.pager a:selected {background-color: #353535; color: white;}

        div#categories a {
            font: bold 1.1em "Arial Narrow", "Franklin Gothic Medium", Arial;
            display: block;
            text-decoration: none; padding: .6em; color: black;
            border-bottom: 1px solid silver;
        }
        div#categories a.selected {background-color: #666; color: white;}
        div#categories a:hover {background-color: #ccc; }
        div#categories a.selected:hover {background-color: #666; }
    </style>
</head>

<body>
    
    <div id="header">
        <div class="title">SPORTS STORE</div>
    </div>
    <div id="categories">
        @{Html.RenderAction("Menu", "Nav", new { highlightCategory = ViewBag.CurrentCategory }); }
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>